FROM ghcr.io/nf-osi/nfportalutils@sha256:dc172f17a8a8576473403e88a7cc63ca6cf6721d3505d920de9ba3de80c761a3

COPY calculate_related_studies.R /calculate_related_studies.R

ENTRYPOINT ["r", "/calculate_related_studies.R"]

