name: Dockerize snapshot

# For only changes in snapshot code,
# rebuild on push to main (which is already vetted in PR to develop)
on:
  push:
    branches:
      - main
    paths:
      - snapshot/**
  pull_request:
    branches:
      - main
    paths:
      - snapshot/**

# Use ghcr registry
env:
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Login against a Docker registry except on PR
      # (confirm that image can be built, but don't push to registry)
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Get short hash for tag
        id: tag
        run: echo "::set-output name=sha7::$(git rev-parse --short $GITHUB_SHA)"

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./snapshot
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-snapshot:latest,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-snapshot:${{steps.tag.outputs.sha7}}
          platforms: linux/amd64
